# Entidades organizacionales mínimas para que los owners del catálogo existan.
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Equipo de plataforma (dueño del Golden Path)
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: payments-team
  description: Equipo de medios de pago
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  description: Usuario invitado del entorno local
spec:
  profile:
    displayName: Guest
  memberOf:
    - platform-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: plataforma-uniandes
  description: Sistema que agrupa los microservicios generados por el Golden Path
spec:
  owner: platform-team